import os
import argparse
from typing import Optional
from mistralai import Mistral

class BloomsMistralRephraser:
    """
    A utility class to use Mistral's API to rephrase and improve vague questions 
    generated by the smaller local T5 model.
    """
    def __init__(self, api_key: str = None, model_name: str = 'mistral-large-latest'):
        key = api_key or os.environ.get("MISTRAL_API_KEY")
        if not key:
            raise ValueError("MISTRAL_API_KEY is missing. Please set the environment variable or pass it to __init__.")
        
        self.client = Mistral(api_key=key)
        self.model_name = model_name
        
        self.system_instruction = (
            "You are an expert educational instructional designer specializing in Bloom's Taxonomy. "
            "Your task is to take a somewhat vague or grammatically awkward question generated by a smaller AI model, "
            "along with the source text (chunk), and the target Bloom's Taxonomy level. "
            "You must ONLY fix the grammar, clarity, and phrasing of the ORIGINAL question so that it explicitly references the concepts in the source text instead of being abstract. "
            "\n\n"
            "CRITICAL: Do NOT invent a completely new question. You must identify what the original poorly-phrased question is trying to ask about, and rewrite THAT EXACT inquiry to make it sound professional and standalone. If the original question asks about 'property X', your improved question must also ask about 'property X'. "
            "\n\n"
            "Do NOT answer the question. Only output the revised question. Maintain the specific Bloom's tag at the beginning of the question.\n\n"
            "CRITICAL CONSTRAINTS FOR STANDALONE QUESTIONS:\n"
            "- The question must be entirely standalone and usable in a general quiz.\n"
            "- Do NOT include phrases like 'based on the text', 'from the given text', or 'in the text'.\n"
            "- Do NOT reference any figure numbers, equation numbers, or table numbers.\n"
            "- Do NOT hallucinate specific numbers or math equations if they are not explicitly and fully defined in the source text.\n\n"
            "Guidelines per level:\n"
            "- [REMEMBER]: Ask to recall facts, define terms, or list items from the topic.\n"
            "- [UNDERSTAND]: Ask to explain ideas, summarize, or paraphrase a concept.\n"
            "- [APPLY]: Ask to use the information in a new situation or demonstrate how it works.\n"
            "- [ANALYZE]: Ask to compare, contrast, break down, or examine relationships.\n"
            "- [EVALUATE]: Ask to judge, critique, or justify a stand.\n"
            "- [CREATE]: Ask to design, propose, or construct something new."
        )

    def generate_prompt(self, source_text: str, generated_question: str, target_level: str) -> str:
        """Constructs the few-shot prompt for the Mistral model."""
        prompt = f"""
Here are some examples of how to improve questions:

--- Example 1 ---
Source Text: The cell membrane controls the movement of substances in and out of cells and organelles.
Target Level: [REMEMBER]
Original Vague Question: [REMEMBER] What is the cell membrane in out cells?
Improved Question: [REMEMBER] What forms the boundary that controls the movement of substances in and out of cells?

--- Example 2 ---
Source Text: The process of photosynthesis takes place in the chloroplasts, where chlorophyll absorbs sunlight to convert carbon dioxide and water into glucose and oxygen.
Target Level: [UNDERSTAND]
Original Vague Question: [UNDERSTAND] Interpret the concept described here: chlorophyll absorbs sunlight.
Improved Question: [UNDERSTAND] Can you explain how chlorophyll absorbs sunlight during the process of photosynthesis?

--- Example 3 ---
Source Text: Newton's Second Law states that Force equals mass times acceleration (F = ma). This means the heavier an object is, the more force is required to accelerate it.
Target Level: [APPLY]
Original Vague Question: [APPLY] How is a heavy object force to accelerate?
Improved Question: [APPLY] How does the mass of a heavy object affect the amount of force required to accelerate it according to Newton's Second Law?

--- Example 4 ---
Source Text: In metaphase, the chromosomes align at the cell's equator. Following this, anaphase involves the separation of the sister chromatids, pulled toward opposite poles.
Target Level: [ANALYZE]
Original Vague Question: [ANALYZE] What is the relationship between the equator and anaphase?
Improved Question: [ANALYZE] How does the alignment of chromosomes at the equator during metaphase relate to their subsequent separation during anaphase?

--- Example 5 ---
Source Text: Renewable energy sources like solar and wind power produce no greenhouse gas emissions during operation, unlike coal power plants which are major contributors to global warming. However, solar and wind are intermittent energy sources.
Target Level: [EVALUATE]
Original Vague Question: [EVALUATE] Assess the solar wind power and coal emissions.
Improved Question: [EVALUATE] How do the greenhouse gas emissions of coal power plants compare to the emissions produced by solar and wind power?

--- Example 6 ---
Source Text: The internal energy of a system changes when heat is added to the system or work is done by it, characterized by the equation Delta U = Q - W.
Target Level: [CREATE]
Original Vague Question: [CREATE] Develop a hypothesis related to: The internal energy of a system changes.
Improved Question: [CREATE] Formulate a hypothesis predicting how the internal energy of a system will change if work is constantly done by it without adding heat.

--- YOUR TASK ---
Source Text: {source_text}
Target Level: {target_level}
Original Vague Question: {generated_question}
Improved Question:"""
        return prompt

    def rephrase(self, source_text: str, generated_question: str) -> str:
        """
        Rephrases the given question based on the source text using the Mistral API.
        Extracts the target Bloom's level from the original question's tag.
        """
        import time
        start_time = time.time()
        print("\n--- REPHRASER CALLED (MISTRAL) ---")
        
        # Ensure we have a valid input
        if not source_text or not generated_question:
            print("Missing source or question. Returning original.")
            return generated_question

        # Extract the Bloom's tag if it exists (e.g., "[ANALYZE]")
        import re
        match = re.search(r'\[(.*?)\]', generated_question)
        target_level = match.group(0) if match else "[UNKNOWN LEVEL]"
        
        print(f"Target level identified: {target_level}")
        prompt = self.generate_prompt(source_text, generated_question, target_level)
        
        try:
            print("Calling Mistral API...")
            chat_response = self.client.chat.complete(
                model=self.model_name,
                messages=[
                    {
                        "role": "system",
                        "content": self.system_instruction
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.4,
            )
            elapsed = time.time() - start_time
            print(f"API Returned in {elapsed:.2f} seconds!")
            return chat_response.choices[0].message.content.strip()
        except Exception as e:
            print(f"Error during Mistral API call: {e}")
            return generated_question # Fallback to original if API fails


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Rephrase generated Bloom's taxonomy questions using Mistral API")
    parser.add_argument("--chunk", type=str, required=True, help="The source text chunk")
    parser.add_argument("--question", type=str, required=True, help="The vaguely generated question with its Bloom's tag")
    parser.add_argument("--api_key", type=str, default=None, help="Mistral API Key (or set MISTRAL_API_KEY env var)")
    
    args = parser.parse_args()
    
    try:
        rephraser = BloomsMistralRephraser(api_key=args.api_key)
        print("\n--- Original ---")
        print(args.question)
        print("\n--- Rephrased by Mistral ---")
        improved = rephraser.rephrase(args.chunk, args.question)
        print(improved)
    except ValueError as ve:
        print(ve)
