import os
import argparse
from typing import Optional
from google import genai
from google.genai import types

class BloomsGeminiRephraser:
    """
    A utility class to use Google's Gemini API to rephrase and improve vague questions 
    generated by the smaller local T5 model.
    """
    def __init__(self, api_key: str = None, model_name: str = 'gemini-2.5-flash'):
        key = api_key or os.environ.get("GEMINI_API_KEY")
        if not key:
            raise ValueError("GEMINI_API_KEY is missing. Please set the environment variable or pass it to __init__.")
        
        self.client = genai.Client(api_key=key)
        self.model_name = model_name
        
        # System instructions heavily guide the model on the persona and constraints
        self.system_instruction = (
            "You are an expert educational instructional designer specializing in Bloom's Taxonomy. "
            "Your task is to take a somewhat vague or grammatically awkward question generated by a smaller AI model, "
            "along with the source text (chunk) that the question is based on, and the target Bloom's Taxonomy level. "
            "You must rewrite the question so that it is grammatically perfect, clear, pedagogically sound, and "
            "strictly aligns with the specified Bloom's cognitive level. "
            "\n\n"
            "Do NOT answer the question. Only output the revised question. Maintain the specific Bloom's tag at the beginning of the question. "
            "Make sure the question explicitly references the concepts in the source text rather than using vague pronouns like 'it' or 'this'.\n\n"
            "Guidelines per level:\n"
            "- [REMEMBER]: Ask to recall facts, define terms, or list items from the text.\n"
            "- [UNDERSTAND]: Ask to explain ideas, summarize, or paraphrase a concept from the text.\n"
            "- [APPLY]: Ask to use the information in a new situation or demonstrate how it works.\n"
            "- [ANALYZE]: Ask to compare, contrast, break down, or examine relationships within the text.\n"
            "- [EVALUATE]: Ask to judge, critique, or justify a stand based on the text.\n"
            "- [CREATE]: Ask to design, propose, or construct something new using the text's principles."
        )

    def generate_prompt(self, source_text: str, generated_question: str, target_level: str) -> str:
        """Constructs the few-shot prompt for the Gemini model."""
        prompt = f"""
Here are some examples of how to improve questions:

--- Example 1 ---
Source Text: The cell membrane controls the movement of substances in and out of cells and organelles.
Target Level: [REMEMBER]
Original Vague Question: [REMEMBER] What is the cell membrane in out cells?
Improved Question: [REMEMBER] What is the primary function of the cell membrane regarding the movement of substances?

--- Example 2 ---
Source Text: The process of photosynthesis takes place in the chloroplasts, where chlorophyll absorbs sunlight to convert carbon dioxide and water into glucose and oxygen.
Target Level: [UNDERSTAND]
Original Vague Question: [UNDERSTAND] Interpret the concept described here: chlorophyll absorbs sunlight.
Improved Question: [UNDERSTAND] Explain in your own words the role of chlorophyll in the process of photosynthesis as described in the text.

--- Example 3 ---
Source Text: Newton's Second Law states that Force equals mass times acceleration (F = ma). This means the heavier an object is, the more force is required to accelerate it.
Target Level: [APPLY]
Original Vague Question: [APPLY] How is a heavy object force to accelerate?
Improved Question: [APPLY] If you have a 10kg box and a 20kg box, how would you use Newton's Second Law to determine the difference in force required to accelerate both at 5 m/s²?

--- Example 4 ---
Source Text: In metaphase, the chromosomes align at the cell's equator. Following this, anaphase involves the separation of the sister chromatids, pulled toward opposite poles.
Target Level: [ANALYZE]
Original Vague Question: [ANALYZE] What is the relationship between the equator and anaphase?
Improved Question: [ANALYZE] Compare the positioning of chromosomes during metaphase with their movement during anaphase.

--- Example 5 ---
Source Text: Renewable energy sources like solar and wind power produce no greenhouse gas emissions during operation, unlike coal power plants which are major contributors to global warming. However, solar and wind are intermittent energy sources.
Target Level: [EVALUATE]
Original Vague Question: [EVALUATE] Assess the solar wind power and coal emissions.
Improved Question: [EVALUATE] Based on the text, justify whether a city should completely replace its coal power plants with solar and wind energy, considering the provided pros and cons.

--- Example 6 ---
Source Text: The internal energy of a system changes when heat is added to the system or work is done by it, characterized by the equation Delta U = Q - W.
Target Level: [CREATE]
Original Vague Question: [CREATE] Develop a hypothesis related to: The internal energy of a system changes. Outline how you would test it.
Improved Question: [CREATE] Design an experiment to verify that the internal energy of a gas changes according to the equation Delta U = Q - W when heat is added.

--- YOUR TASK ---
Source Text: {source_text}
Target Level: {target_level}
Original Vague Question: {generated_question}
Improved Question:"""
        return prompt

    def rephrase(self, source_text: str, generated_question: str) -> str:
        """
        Rephrases the given question based on the source text using the Gemini API.
        Extracts the target Bloom's level from the original question's tag.
        """
        import time
        start_time = time.time()
        print("\n--- REPHRASER CALLED ---")
        
        # Ensure we have a valid input
        if not source_text or not generated_question:
            print("Missing source or question. Returning original.")
            return generated_question

        # Extract the Bloom's tag if it exists (e.g., "[ANALYZE]")
        import re
        match = re.search(r'\[(.*?)\]', generated_question)
        target_level = match.group(0) if match else "[UNKNOWN LEVEL]"
        
        print(f"Target level identified: {target_level}")
        prompt = self.generate_prompt(source_text, generated_question, target_level)
        
        try:
            print("Calling google-genai API...")
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=self.system_instruction,
                    temperature=0.4,
                )
            )
            elapsed = time.time() - start_time
            print(f"API Returned in {elapsed:.2f} seconds!")
            return response.text.strip()
        except Exception as e:
            print(f"Error during Gemini API call: {e}")
            return generated_question # Fallback to original if API fails


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Rephrase generated Bloom's taxonomy questions using Gemini API")
    parser.add_argument("--chunk", type=str, required=True, help="The source text chunk")
    parser.add_argument("--question", type=str, required=True, help="The vaguely generated question with its Bloom's tag")
    parser.add_argument("--api_key", type=str, default=None, help="Gemini API Key (or set GEMINI_API_KEY env var)")
    
    args = parser.parse_args()
    
    try:
        rephraser = BloomsGeminiRephraser(api_key=args.api_key)
        print("\n--- Original ---")
        print(args.question)
        print("\n--- Rephrased by Gemini ---")
        improved = rephraser.rephrase(args.chunk, args.question)
        print(improved)
    except ValueError as ve:
        print(ve)
